### PR TITLE
Added packages

### PR DESCRIPTION
**Pull request by interkosmos**
Added packages, same as in the [pull request for the old repo](https://github.com/fortran-lang/fpm-registry/pull/63).

### CODE REVIEW

**Comment by awvwgk** [comment]
#build_preview

**Comment by interkosmos** [comment]
I’ve expected the CI pipeline to re-build the page. Or am I missing something?

**Comment by henilp105** [comment]
Thanks sir, actually I discovered an issue in the pr preview CI , we will be resolving it in the upcoming PR.
Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
Philipp @interkosmos, can you suggest anyone for helping with reviewing those package additions?

**Comment by awvwgk** [comment]
#build_preview

**Review by everythingfunctional — APPROVED** [review]
:+1:

**Comment by interkosmos** [comment]
Hi Sebastian @awvwgk, sorry for the late reply. I would be willing to review package additions in future.

**Comment by ivan-pi** [comment]
I will do my best to review the packages soon.

**Review by awvwgk — APPROVED** [review]
Looks good to me.

**Review by everythingfunctional — APPROVED** [review]
:+1:

**Pull request merged**
