### PR TITLE
Intel Updates for compilers.md

### PR DESCRIPTION
**Pull request by greenrongreen**
01 Jan 2023 updates to intel Fortran compiler

### CODE REVIEW

**Review by awvwgk — APPROVED** [review]
Thanks for sharing.

**Review by milancurcic — APPROVED** [review]
Thanks @greenrongreen for the update!

**Comment by certik** [comment]
Thanks @greenrongreen !

**Comment by band-a-prend** [comment]
Could this changes be merged please into weblate English index.po file?

**Pull request merged**
