### PR TITLE
Update intrinsics descriptions

### PR DESCRIPTION
**Pull request by urbanjost**

### CODE REVIEW

**Comment by henilp105** [comment]
Thanks sir.

**Comment by henilp105** [comment]
#build_preview

**Review by awvwgk — APPROVED** [review]
Looks good to me, thanks.

**Comment by urbanjost** [comment]
#build preview

**Comment by henilp105** [comment]
#build_preview

**Comment by urbanjost** [comment]
Not sure if the index files should be changed manually to add OUT_OF_RANGE.md to the intrinsics. The index pages in the previous rendition of the web page had  markdown index pages in the same directory as the procedure descriptions which were changed when a new procedure was added. Not sure exactly what the process should be now. Have a few more like
o XOR
o REDUCE
x OUT_OF_RANGE
o COSHAPE
o FAILED_IMAGES
o GET_TEAM
o IMAGE_STATUS
o LCOBOUND
o STOPPED_IMAGES
o TEAM_NUMBER
o UCOBOUND
o RANDOM_INIT

that need added. If anyone else would like to create these, please indicate it.

**Comment by henilp105** [comment]
The procedure to add new files we would have to make a md file put in inside the _pages folder then add an entry in the index.md of intrinsics folder. Thanks sir.

**Comment by urbanjost** [comment]
@p-costa -- sorry for duplicating your changes. I was doing a bulk review and missed you had already done SIGN till I was making the fork. I had to change over to the new methods and spent quite a bit of time focused on setting up and understanding (a work in progress) the new infrastructure.

Now that a new stable platform is available there are still the missing procedures listed above and descriptions of the standard modules and reviews of the current documents.  

You got far enough to actually make changes, so I hope you have time to make other contributions. I have really been hoping this would be a community project. I am hoping we can built up more complete documentation for co-arrays and atomic functions in particular, as that is probably the weakest section at this point but I initially focused on getting enough of a description of everything to get this published -- I know there is still plenty of room for improvements :>

**Comment by p-costa** [comment]
Thank you @urbanjost! I should have looked better and realized that there was more work to do. And since you are the original author of the manpages, I thought it would be best to simply let you take over on these specific changes. I am always happy to contribute to these efforts, and I hope I will have many chances to give my inputs, which will likely be tiny compared to what all you CC'd in this thread have already contributed.

And thank you very much for putting these intrinsic manpages together, by the way, they are really useful!

**Comment by awvwgk** [comment]
> x OUT_OF_RANGE --done, needs added to index

I added the new page to the respective index in https://github.com/fortran-lang/webpage/commit/b1345136c4a06dce2d5f67248c0f1cad3691dc52.

**Comment by urbanjost** [comment]
Thanks for changing the index. I was not positive this was the (only) file to change.  I will add that as an example to my notes.

**Pull request merged**
