### PR TITLE
Fix bing Temporary Patch (gh-pages) 

### LINKED ISSUE #222: Generate sitemap.xml for crawlers
Can be done via https://sphinx-sitemap.readthedocs.io/en/latest/index.html for sphinx with translations.

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to resolve #222 , Please refer : https://fortran-lang.discourse.group/t/4942 

This is a temporary patch to fix the bing **directly** via **gh-pages** as it seems the most likely cause could be `HTML redirection` , as we don't have the functionality to add  `301 Redirect` in gh-pages, thus this PR is a temporary fix to this redirection bug , and this same method of redirection is also used in the fpm-docs repository and we seem to reproduce the same problem for the fpm-docs repository as well.

Thanks and Regards,
Henil

CC @awvwgk @certik

### CODE REVIEW

**Comment by awvwgk** [comment]
Henil @henilp105, would it be possible to move the English language tree to fortran-lang.org and maybe have a duplicated one at firtran-lang.org/en? This way we don't need the additional redirect logic. Only thing to be careful about is that the language navigation works from both trees.

**Comment by henilp105** [comment]
@awvwgk , we can move the English language tree (language redirects can be handled in  sphinx templates for languages) but the redirects of older webpage (jekyll) will conflict with the English language tree ( can we disable the older redirects for jekyll build ? ).

**Comment by awvwgk** [comment]
We can remove all redirects which are not needed anymore once the English tree is in the page door.

**Comment by certik** [comment]
I would remove all redirects and have the english page copied at fortran-lang.org/. It looks better anyway. This can be done with a script that runs after sphinx is finished.

**Comment by henilp105** [comment]
Thanks @awvwgk @certik , can you Please Review #283 .

**Pull request closed without merging**
