### PR TITLE
Google Summer of Code’22: Port fortran-lang.org to Sphinx PR #2

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to port the Existing site of fortran-lang.org to sphinx.
This GSoC’22 project is done by Henil Shalin Panchal under the Guidance of GSoC mentors Sebastian Ehlert @awvwgk and Rohit Goswami @HaoZeke .I request all the members of the organisation fortran-lang @fortran-lang/admins  @fortran-lang please review this PR and add suggestions and comments on this PR.

https://summerofcode.withgoogle.com/programs/2022/projects/L28fukIz

This PR Fixes the Following Issues :
- [x] #7 
- [x] #9 
- [x] #6
- [x] #11  ( updated .po files for translation )
 
Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk @HaoZeke

### CODE REVIEW

**Comment by henilp105** [comment]
#build_preview

**Comment by henilp105** [comment]
#build_preview

**Comment by henilp105** [comment]
#delete_preview

**Comment by awvwgk** [comment]
Can you move the guides in a contributing subdirectory?

**Comment by awvwgk** [comment]
Also, can you remove the po files from the commit for now. It just makes a huge diff.

**Comment by henilp105** [comment]
sir, but how to move them to a sub directory as we are using dirhtml to make directories.

**Comment by henilp105** [comment]
yes sir , I will remove them.

**Comment by awvwgk** [comment]
> sir, but how to move them to a sub directory as we are using dirhtml to make directories.

See https://github.com/fortran-lang/webpage/pull/23

**Pull request closed without merging**
