### PR TITLE
Fix resolution of included files and search paths in minibook

### PR DESCRIPTION
**Pull request by p-costa**
To close https://github.com/fortran-lang/fortran-lang.org/issues/416

### CODE REVIEW

**Comment by henilp105** [comment]
Thanks for fixing @p-costa . We will be resolving the build preview thing soon.

Thanks and Regards,
Henil Shalin Panchal

**Comment by henilp105** [comment]
#build_preview

**Comment by p-costa** [comment]
Thank you @henilp105 for your great work on the new website!

**Comment by henilp105** [comment]
Thank you sir, Your PR preview is available at : https://fortran-lang.github.io/webpage/pr/25/ .

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by awvwgk** [comment]
> Your PR preview is available

Very cool, can we also insert a banner to note that this page is a preview?

**Comment by henilp105** [comment]
Yes sir, I will Implement it . Thanks sir.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Comment by henilp105** [comment]
#delete_preview

**Pull request merged**
