### PR TITLE
fix canonical links for crawlers

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to resolve https://github.com/fortran-lang/webpage/issues/222 , Please refer : https://fortran-lang.discourse.group/t/4942 .

This would add a custom canonical link tag to all the pages of the webpage.

Thanks and Regards,
Henil

CC @awvwgk @certik

### CODE REVIEW

**Comment by certik** [comment]
What is the purpose of the canonical tag? The url seem long and pointing to some github.io url, while I would think our canonical page is "https://fortran-lang.org/".

**Comment by henilp105** [comment]
@certik the canonical links are used to show a crawler that the duplicate content is available in this link and don't penalise/remove this page from the search engine as they are related ( even if you have crawled the older site and find this as a duplicate).

**Comment by certik** [comment]
I see. And the link that you put into the `canonical` is the "main" content, or the "secondary" content?

To me, the word canonical means the "main" content, thus `https://fortran-lang.org/`.

**Comment by henilp105** [comment]
@certik yes, we should add this code to the duplicate site / older site.

**Comment by certik** [comment]
@henilp105 ok, ping me once you have a PR ready for reivew.

**Pull request closed without merging**
