### PR TITLE
Fix redirects

### LINKED ISSUE #222: Generate sitemap.xml for crawlers
Can be done via https://sphinx-sitemap.readthedocs.io/en/latest/index.html for sphinx with translations.

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to resolve #222 , Please refer : https://fortran-lang.discourse.group/t/4942 

I have shifted the en/ to root directory and set the language redirections for other languages.

This is a permant patch to fix the bing as it seems the most likely cause could be `HTML redirection` , as we don't have the functionality to add  `301 Redirect` in gh-pages, thus this PR is a permanant fix to this redirection bug , and this same method of redirection is also used in the fpm-docs repository and we seem to reproduce the same problem for the fpm-docs repository as well.

Thanks and Regards,
Henil

CC @awvwgk @certik

### CODE REVIEW

**Comment by henilp105** [comment]
#build_preview

**Comment by certik** [comment]
The build preview says 404. How can I check that this PR works? Probably locally. I will have time tomorrow to look into this.

**Comment by henilp105** [comment]
@certik it is due to the preview build restrictions you can checkout it here : https://fortran-lang.org/pr/283/en/ . it would be great if you could test it locally. Thanks.

**Comment by certik** [comment]
I build it using the instructions in the README and when I go to the webpage, I can see:

Screen Shot 2023-05-23 at 3 12 53 PM

If I click on a given language, then everything works. But shouldn't I see the English version at the root link?

**Comment by certik** [comment]
I think you move things around in the workflow. How about you create a script that you call from the CI, that we can also run locally? Then we can test it that everything works.

**Comment by awvwgk** [comment]
I recommend to directly change this in the `build.py` script rather than the CI workflow:

```diff
diff --git a/build.py b/build.py
index 9e50d513b..41652158e 100644
--- a/build.py
+++ b/build.py
@@ -62,7 +62,7 @@ If you are not redirected automatically, follow the <a href='{0}'>link</a>.
 """
 
 
-def build_docs(language: str) -> None:
+def build_docs(language: str, root: bool) -> None:
     """
     Build the documentation for a single language.
 
@@ -78,7 +78,7 @@ def build_docs(language: str) -> None:
             "-b",
             "dirhtml",
             str(srcdir),
-            str(outdir / language),
+            str(outdir) if root else str(outdir / language),
             f"-Dlanguage={language}",
         ],
         cwd=root,
@@ -119,11 +119,11 @@ def build_all(redirects: Dict[str, str], languages: List[str]) -> None:
         List of languages to build the documentation for.
     """
 
-    for language in languages:
-        build_docs(language)
-
     build_redirects(redirects, languages[0])
 
+    for language in languages:
+        build_docs(language, language == languages[0])
+
 
 if __name__ == "__main__":

```

**Comment by certik** [comment]
@henilp105 go ahead and do the change that @awvwgk suggested. Then ping me, I'll test it again locally.

**Comment by henilp105** [comment]
Sure, @certik I have made the changes , can you please test it locally ?

**Review by awvwgk — APPROVED** [review]

**Pull request merged**
