### PR TITLE
Adjust title order in learning toctree and fix some typos

### PR DESCRIPTION
**Pull request by 0ut0fcontrol**
Thank you for the tutorial. I am new at Fortran (I only wrote python before) and found the tutorial helpful.

But the tutorial toctree is alphabetical. I adjust the title order in https://fortran-lang.org/en/learn/quickstart/ sidebar
based on https://github.com/fortran-lang/webpage/blob/main/data/learning.yml.

I also fix some typos in my reading.

Welcome review. I am happy to modify if something I did wrong.

### CODE REVIEW

**Comment by henilp105** [comment]
Thanks @0ut0fcontrol sir.

**Comment by henilp105** [comment]
#build_preview

**Comment by 0ut0fcontrol** [comment]
Do I need to run `python3 intl.py` and commit?  @henilp105

**Comment by henilp105** [comment]
@0ut0fcontrol please feel free to do so. Thanks

**Comment by 0ut0fcontrol** [comment]
I can rebase this branch or revert commit 7fa5c1a11174804020dfaa549c09fe51d9a22cb8 to resolve the conflicts, which one do you like?

**Comment by 0ut0fcontrol** [comment]
#build_preview

**Review by awvwgk — APPROVED** [review]
Thanks for sharing. Looks good to me.

**Pull request merged**
