### PR TITLE
Gotchas

### PR DESCRIPTION
**Pull request by PierUgit**
Creation of a "gotchas" page (currently located in the Learn/Quickstart section) to illustrate the most common Fortran traps to newcomers, as discussed here : https://fortran-lang.discourse.group/t/tsoding-on-fortran/6102/63?u=pieru

### CODE REVIEW

**Comment by henilp105** [comment]
#build_preview

**Comment by henilp105** [comment]
@PierUgit , Do you think this PR is good to merge as it seems to be a useful addition to the webpage.

**Comment by PierUgit** [comment]
Looks OK to me!

**Review by henilp105 — APPROVED** [review]
Thanks @PierUgit , Looks good to me.

**Comment by gnikit** [comment]
Sorry guys completely missed that. Good job on this @PierUgit and thanks for PR!

**Pull request merged**
