### PR TITLE
Fixes two typos in the Learn page

### PR DESCRIPTION
**Pull request by vmagnin**
- Concerning WG5, as the `description:` field is void, the "None" string appeared on the webpage. I have removed that field to avoid that.
- I have deleted a ")" without a corresponding "("

### CODE REVIEW

**Comment by henilp105** [comment]
#build_preview

**Comment by henilp105** [comment]
Thanks sir, @vmagnin .

**Review by awvwgk — APPROVED** [review]
Good catch.

**Comment by henilp105** [comment]
#delete_preview

**Pull request merged**
