### PR TITLE
Use MyST markdown for learn page

### PR DESCRIPTION
**Pull request by awvwgk**
Result should be visually identical to the RST version. The nesting depth is visible in the outmost scope for MyST due to the matching of colon-fences, while in RST the nesting is due to semantic indentation only affecting the inner scopes.

**Related**

- #10

### CODE REVIEW

**Comment by henilp105** [comment]
Thanks sir, I will be patching this.

**Comment by awvwgk** [comment]
Feel free to start from this branch.

**Comment by henilp105** [comment]
Thanks sir.

**Comment by certik** [comment]
Thanks @awvwgk ! This seems about the same readable in both rst and md to me.

**Comment by henilp105** [comment]
PR #24 resolves this. thus, I request this issue to be closed.

Thanks and Regards,
Henil Shalin Panchal

CC @awvwgk

**Pull request closed without merging**
