### PR TITLE
add: Fortran Playground Code links

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to add The fortran playground links to every fortran code in the learn section. I have currently **not added the links to intrinsics** as feature is in testing phase.

Thanks and Regards,
Henil

CC @awvwgk

### CODE REVIEW

**Comment by henilp105** [comment]
#build_preview

**Comment by henilp105** [comment]
#build_preview

**Comment by milancurcic** [comment]
This is great, thank you for making it. A few suggestions:

* Reword as "Run in the playground"
* Remove the logo from the playground; I think it adds noise and at this point the reader knows it's Fortran
* Link under the snipper instead of above; we want the reader to read the snippet first, and then run it in the playground if they want to.
* Have the link open the playground in a new tab
* Either provide the link only for snippets that will compile and run, or we need to update the snippets to be complete. It will be a lot of work to update the snippets to be complete, so I suggest for now to exclude the link if the snippet is not complete.

**Comment by henilp105** [comment]
@milancurcic how should we detect incomplete snippets ?

**Comment by milancurcic** [comment]
Oh, are the links populated automatically for every snippet? I see. I thought you added them by hand and could be excluded by hand. In that case, I don't have a good idea at the moment. We could leave it as you have it now, and let the reader figure out that they need to fix an incomplete snippet for it to compile and run.

**Comment by henilp105** [comment]
@milancurcic Will rebase it.

**Comment by henilp105** [comment]
@milancurcic We won't be able to add it below as i have added a node with link in the caption using doc util nodes of sphinx.

**Comment by henilp105** [comment]
#build_preview

**Comment by henilp105** [comment]
#delete_preview

**Pull request closed without merging**
