### PR TITLE
add: Language translations version switcher and fix Polish translation

### LINKED ISSUE #172: Use full language name in language selector
Currently only the language identifier is given in the language selection menu. It might be more intuitive to have the full name of the language there. The full name of the language should preferably be written in the actual language itself, to make it easier to find for native speakers. Not sure what the best way of sorting is in that case.

### LINKED ISSUE #180: Polish translation is not built
https://github.com/fortran-lang/webpage/blob/main/data/languages.yml does not contain the Polish language code (pl) and therefore the language is missing in the deployed page.

### PR DESCRIPTION
**Pull request by henilp105**
This PR is to add language Translations to the fortran-lang.org site.

This PR Resolves : 
closes #172 
Updates Dependencies #178 #179
Closes #180 

Thanks and Regards,
Henil 

CC @awvwgk

### CODE REVIEW

**Comment by awvwgk** [comment]
German = Deutsch
Dutch = Nederlands

**Comment by awvwgk** [comment]
cc @certik, @14NGiestas, @band-a-prend

**Comment by band-a-prend** [comment]
Russian (ru) = Русский

**Comment by 14NGiestas** [comment]
Portuguese (pt) = Português

**Review by awvwgk — APPROVED** [review]
Thanks for sharing, looks good to me.

**Pull request merged**
