### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Fortran programming language/Fortran webpage](https://hosted.weblate.org/projects/fortran-lang/webpage/).

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by awvwgk** [comment]
@zoziha @St-Maxwell @Euler-37 @ansatzX Let me know when the Chinese translation is ready to go.

**Comment by zoziha** [comment]
Fortran-lang's official website's content translation workload is still very large. At present, 11% of the Chinese translation has been completed.
@awvwgk , I'm in favor of merging this PR first, and then complete the rest of the work in stages in subsequent PRs.

**Comment by zoziha** [comment]
It seems that the Chinese translation lost a small part of the existing work due to the merger of #49 and #114 four hours ago.

**Comment by awvwgk** [comment]
> It seems that the Chinese translation lost a small part of the existing work due to the merger of #49 and #114 four hours ago.

If the source strings changes the translations will need to be updated. Usually due to similarity of the new string the previous one the translation should be kept and the *fuzzy* / *needs editing* flag is set, still a review by a translator is needed.

> Fortran-lang's official website's content translation workload is still very large.

Thanks a lot for your effort so far, 11% is already quite impressive.

> I'm in favor of merging this PR first, and then complete the rest of the work in stages in subsequent PRs.

Will go ahead and merge than.

**Pull request merged**
